export const styles = {
    page: {
        minHeight: "100vh",
        background: "radial-gradient(ellipse at 30% 10%, #ffe0ec 0%, #fce8f3 30%, #f9d6ea 60%, #f0c0de 100%)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "'Georgia', serif",
        padding: "2rem 1rem",
        position: "relative",
        overflow: "hidden",
    },
    blob1: {
        position: "fixed",
        top: "-80px",
        left: "-80px",
        width: 320,
        height: 320,
        borderRadius: "50%",
        background: "radial-gradient(circle, #ffadd1aa, #ff80b500)",
        filter: "blur(40px)",
        pointerEvents: "none",
    },
    blob2: {
        position: "fixed",
        bottom: "-100px",
        right: "-60px",
        width: 400,
        height: 400,
        borderRadius: "50%",
        background: "radial-gradient(circle, #ff6eb4aa, #ff006600)",
        filter: "blur(60px)",
        pointerEvents: "none",
    },
    blob3: {
        position: "fixed",
        top: "50%",
        left: "60%",
        width: 200,
        height: 200,
        borderRadius: "50%",
        background: "radial-gradient(circle, #ffc2d988, transparent)",
        filter: "blur(30px)",
        pointerEvents: "none",
    },
    card: {
        background: "linear-gradient(160deg, rgba(255,255,255,0.85) 0%, rgba(255,230,242,0.9) 100%)",
        backdropFilter: "blur(20px)",
        border: "1.5px solid rgba(255,150,190,0.4)",
        borderRadius: "24px",
        padding: "2.5rem 2rem",
        width: "100%",
        maxWidth: "440px",
        boxShadow: "0 8px 60px rgba(255,100,160,0.2), 0 2px 20px rgba(255,150,190,0.15), inset 0 1px 0 rgba(255,255,255,0.9)",
        position: "relative",
        overflow: "hidden",
    },
    shimmerLine: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 3,
        background: "linear-gradient(90deg, #ffb3cc, #ff4d8f, #ffb3cc)",
        borderRadius: "24px 24px 0 0",
    },
    header: {
        textAlign: "center",
        marginBottom: "2rem",
    },
    lockRing: {
        width: 60,
        height: 60,
        margin: "0 auto 0.8rem",
        borderRadius: "50%",
        background: "linear-gradient(135deg, #ffd6e7, #ffaacb)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        boxShadow: "0 4px 20px rgba(255,100,150,0.3)",
    },
    lockEmoji: {
        fontSize: "1.8rem",
    },
    title: {
        margin: 0,
        fontSize: "2.2rem",
        fontWeight: "400",
        color: "#c0306a",
        letterSpacing: "0.2em",
        textTransform: "uppercase",
        fontFamily: "'Georgia', serif",
    },
    subtitle: {
        margin: "0.4rem 0 0",
        color: "#d06090",
        fontSize: "0.78rem",
        letterSpacing: "0.12em",
        textTransform: "uppercase",
    },
    passwordBox: {
        background: "linear-gradient(135deg, rgba(255,220,235,0.6), rgba(255,200,220,0.4))",
        border: "1.5px solid rgba(255,130,170,0.35)",
        borderRadius: "12px",
        padding: "1.3rem 1rem",
        textAlign: "center",
        cursor: "pointer",
        position: "relative",
        marginBottom: "1.2rem",
        minHeight: 72,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        transition: "all 0.2s",
    },
    pwInner: {
        width: "100%",
    },
    passwordText: {
        color: "#8c1a45",
        fontFamily: "'Courier New', monospace",
        fontSize: "1rem",
        wordBreak: "break-all",
        lineHeight: 1.6,
    },
    copyHint: {
        fontSize: "0.68rem",
        color: "#d080a8",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        transition: "color 0.2s",
    },
    strengthRow: {
        display: "flex",
        alignItems: "center",
        gap: "0.8rem",
        marginBottom: "1.5rem",
    },
    strengthLabelLeft: {
        color: "#c07090",
        fontSize: "0.72rem",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        minWidth: 52,
    },
    strengthLabelRight: {
        fontSize: "0.72rem",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        minWidth: 56,
        textAlign: "right",
        fontWeight: "bold",
    },
    strengthBar: {
        flex: 1,
        height: 5,
        background: "rgba(255,170,200,0.3)",
        borderRadius: 4,
        overflow: "hidden",
    },
    strengthFill: {
        height: "100%",
        borderRadius: 4,
        transition: "width 0.5s ease, background 0.5s ease",
    },
    section: {
        marginBottom: "1.5rem",
    },
    sectionHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: "0.7rem",
    },
    sectionTitle: {
        color: "#c07090",
        fontSize: "0.72rem",
        letterSpacing: "0.15em",
        textTransform: "uppercase",
    },
    sectionValue: {
        color: "#d03070",
        fontSize: "0.8rem",
        fontFamily: "monospace",
        fontWeight: "bold",
    },
    keywordInput: {
        width: "100%",
        padding: "0.75rem",
        borderRadius: "8px",
        border: "1px solid rgba(255,160,195,0.4)",
        background: "rgba(255,255,255,0.5)",
        fontFamily: "'Courier New', monospace",
        fontSize: "0.9rem",
        color: "#c0306a",
        outline: "none",
        boxSizing: "border-box",
    },
    slider: {
        width: "100%",
        cursor: "pointer",
    },
    optionsGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "0.6rem",
        marginTop: "0.7rem",
    },
    optionBtn: {
        background: "rgba(255,220,235,0.4)",
        border: "1.5px solid rgba(255,160,195,0.3)",
        borderRadius: "10px",
        padding: "0.75rem",
        cursor: "pointer",
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        gap: "0.2rem",
        position: "relative",
        transition: "all 0.2s",
    },
    optionBtnActive: {
        background: "rgba(255,180,210,0.35)",
        border: "1.5px solid rgba(255,80,140,0.5)",
        boxShadow: "0 0 14px rgba(255,80,140,0.15)",
    },
    optionIcon: {
        fontSize: "0.82rem",
        fontFamily: "monospace",
        fontWeight: "bold",
    },
    optionLabel: {
        color: "#c07090",
        fontSize: "0.68rem",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
    },
    optionDot: {
        position: "absolute",
        top: 8,
        right: 8,
        width: 7,
        height: 7,
        borderRadius: "50%",
        background: "#ff4d8f",
        boxShadow: "0 0 8px #ff4d8fcc",
    },
    generateBtn: {
        width: "100%",
        padding: "1rem",
        background: "linear-gradient(135deg, #ff80b5, #e8235e)",
        border: "none",
        borderRadius: "12px",
        color: "#fff",
        fontSize: "0.85rem",
        fontWeight: "bold",
        letterSpacing: "0.2em",
        textTransform: "uppercase",
        cursor: "pointer",
        fontFamily: "'Georgia', serif",
        boxShadow: "0 6px 24px rgba(232,35,94,0.35)",
        transition: "all 0.2s",
        position: "relative",
        overflow: "hidden",
    },
    footer: {
        textAlign: "center",
        color: "#d090b0",
        fontSize: "0.65rem",
        marginTop: "1.2rem",
        letterSpacing: "0.05em",
        marginBottom: 0,
    },
};

export const css = `
  .pw-box:hover { border-color: rgba(255,80,140,0.5) !important; box-shadow: 0 4px 20px rgba(255,100,150,0.15); }
  .pw-box:hover .copy-hint { color: #e8235e !important; }
  .option-btn:hover { background: rgba(255,200,220,0.5) !important; border-color: rgba(255,100,160,0.5) !important; }
  .gen-btn:hover { transform: translateY(-2px); box-shadow: 0 10px 32px rgba(232,35,94,0.5) !important; }
  .gen-btn:active { transform: translateY(0); }
  .slider { -webkit-appearance: none; height: 5px; background: linear-gradient(to right, #ff4d8f, #ffc2d9); border-radius: 4px; outline: none; }
  .slider::-webkit-slider-thumb { -webkit-appearance: none; width: 18px; height: 18px; border-radius: 50%; background: linear-gradient(135deg, #ff80b5, #e8235e); cursor: pointer; box-shadow: 0 0 10px rgba(255,80,140,0.6); border: 2px solid white; }
`;
